apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-notifications
  template:
    metadata:
      labels:
        app: aks-notifications
    spec:
      containers:
        - image: xineeeee/rso:2023-01-03-17-29-28
          name: aks-notifications
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://mel.db.elephantsql.com/pwxulljg
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: pwxulljg
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: Z12RzWPHnZ3ioS5r4J0QCD_NFwUumEqv
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP



---

apiVersion: v1
kind: Service
metadata:
  name: aks-notifications
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: aks-notifications
