apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-deployment-load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-notifications-load
  template:
    metadata:
      labels:
        app: aks-notifications-load
    spec:
      containers:
        - image: xineeeee/rso:blabla3
          name: aks-notifications-load
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://babar.db.elephantsql.com/cmklvtuw
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: cmklvtuw
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: nEu3BfbTr4jIQTaegoMsV2XEmBuABWTs
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP



---

apiVersion: v1
kind: Service
metadata:
  name: aks-notifications-load
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: aks-notifications-load
