kumuluzee:
  name: image-catalog-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  health:
    checks:
      http-health-check:
        connection-url: http://20.82.85.106/

  cors-filter:
    annotations:
      my-resource:
        allow-origin: "*"
        allow-subdomains: true
        supported-methods: "GET, POST, HEAD, OPTIONS, PUT, DELETE"

  datasources:
    - jndi-name: jdbc/NotificationsDS
      connection-url: jdbc:postgresql://localhost:5432/image-metadata
      username: dbuser
      password: postgres
      max-pool-size: 20

rest-properties:
  maintenance-mode: false
